-- ------------------------------
-- desc: generated by xls2data.py
-- source: 场景加载配置表.xls
-- sheet: 场景加载配置表
-- ------------------------------


Data = {
	['startScene'] = {
		['path'] = '',--'Assets/Scenes/s001/s001.unity',
		['level'] = 'StartScene',
	},
	['coinScene'] = {
		['path'] = '',
		['level'] = 'CoinScene',
	},
	['loginScene'] = {
		['path'] = '',
		['level'] = 'login',
	},
	['battleScene0_0'] = {
		['path'] = '',
		['level'] = 'BattleScene0_0',
	},
	['battleScene0_1'] = {
		['path'] = '',
		['level'] = 'BattleScene0_1',
	},
	['battleScene0_2'] = {
		['path'] = '',
		['level'] = 'BattleScene0_2',
	},
	['battleScene1'] = {
		['path'] = '',
		['level'] = 'BattleScene1',
	},
	['battleScene2'] = {
		['path'] = '',
		['level'] = 'BattleScene2',
	},
	['copyScene'] = {
		['path'] = '',
		['level'] = 'CopyScene',
	},
	['settingScene'] = {
		['path'] = '',
		['level'] = 'SettingScene',
	},	
	['selectScene'] = {
		['path'] = '',
		['level'] = 'SelectScene',
	},	
}
